mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),   # <slug>는 한글 처리가 안되므로 정규식 이용
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),    # 자릿수를 제한하고 싶으면 정규식 이용
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    path('add/', views.BookmarkCreateView.as_view(), name="add"),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static  # static 함수는 정적 파일을 처리하기 위해 그에 맞는 url 패턴을 반환하는 함수
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('photo/', include('photo.urls')),
    path('blog/', include('blog.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')), # 장고의 인증 URLconf를 가져와서 사용, /login/, /logout/ 등이 정의되어있고 앞에 붙이고 싶은 건 앞에 쓰면 됨.
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# settings.MEDIA_URL로 정의된 /media/ URL 요청이 오면 django.views.static.serve() 뷰 함수가 처리하고
# 이 뷰함수에 document_root = settings.MEDIA_ROOT 키워드 인자가 전달됨.
# static.serve() 함수는 개발용이고 상용에는 httpd, nginx 등 웹 서버 프로그램을 사용함.

mysite/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns=[
    path('', views.AlbumLV.as_view(), name='index'),
    path('album/', views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale= 1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:80px;">

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <span class="navbar-brand font-weight-bold font-italic">Django Web Programming</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link " href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn ">
                    <a class="nav-link " href="{% url 'bookmark:index' %}">Bookmark</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link " href="{% url 'photo:index' %}">Photo</a>
                </li>
                <!-- dropdown -->
                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Util</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                        <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                    </ul>
                </li>

                 <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                        <a class="dropdown-item" href="{% url 'blog:add' %}">Blog</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                        <a class="dropdown-item" href="{% url 'blog:change' %}">Blog</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                    </div>
                </li>
            </ul>

            <!-- search -->
            <form class="form-inline my-2" action="" method="post">
                {% csrf_token %}
                <input class="form-control mr-10" type="search" placeholder="global search" name="search_word">
            </form>
            <!-- userinfo -->
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a> <!-- 다음 인자 중에서 False가 아닌 첫 인자를 선택-->
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- awesome font -->
<script src="https://kit.fontawesome.com/48742a1bb0.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image{
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title{
    color: #c80;
    font-weight: bold;
}
.powered{
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap</h4>
</div>

<hr style="margin: 10px 0;">

<div class="content row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>Bookmark is a Uniform Resource Identifier (URI)</p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>This application makes it possible to log daily events or write your own interests</p>
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-secondary">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2022 DjangoBook by hb</div>
</footer>
{% endblock %}