mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),   # <slug>는 한글 처리가 안되므로 정규식 이용
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),    # 자릿수를 제한하고 싶으면 정규식 이용
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static  # static 함수는 정적 파일을 처리하기 위해 그에 맞는 url 패턴을 반환하는 함수
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('photo/', include('photo.urls')),
    path('blog/', include('blog.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')), # 장고의 인증 URLconf를 가져와서 사용, /login/, /logout/ 등이 정의되어있고 앞에 붙이고 싶은 건 앞에 쓰면 됨.
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# settings.MEDIA_URL로 정의된 /media/ URL 요청이 오면 django.views.static.serve() 뷰 함수가 처리하고
# 이 뷰함수에 document_root = settings.MEDIA_ROOT 키워드 인자가 전달됨.
# static.serve() 함수는 개발용이고 상용에는 httpd, nginx 등 웹 서버 프로그램을 사용함.

mysite/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns=[
    path('', views.AlbumLV.as_view(), name='index'),
    path('album/', views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

mysite/photo/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)   # 모델을 import 해도 되고, "앱명.테이블명"도 가능

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = models.ImageField('IMAGE', upload_to='SorlPhoto/%Y')
    upload_dt = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))


class Publication(models.Model):
    title = models.CharField(max_length=30)
    albums = models.ManyToManyField(Album)

    def __str__(self):
        return self.title

mysite/photo/forms.py
from django.forms import inlineformset_factory
from photo.models import Album, Photo

PhotoInlineFormset = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

mysite/photo/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from photo.models import Album, Photo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
from photo.forms import PhotoInlineFormset


class AlbumLV(ListView):
    model = Album
    template_name = "photo/album_list.html"

class AlbumDV(DetailView):
    model = Album
    template_name = "photo/album_detail.html"

class PhotoDV(DetailView):
    model = Photo
    template_name = "photo/photo_detail.html"

class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    template_name = "photo/photo_form.html"
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    template_name = "photo/photo_form.html"
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    template_name = "photo/photo_confirm_delete.html"
    success_url = reverse_lazy('photo:index')

#--- Change-list/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    model = Album
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    template_name = "photo/album_confirm_delete.html"
    success_url = reverse_lazy('photo:index')

#--- (InlineFormSet) Create/Update for Album
class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    template_name = "photo/album_form.html"
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormset(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormset()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album
    template_name = "photo/album_form.html"
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormset(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

mysite/photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}

<h1>Album Change - {{user}}</h1>

<table class="table table-striped table-bordered table-condensed">

    <thead>
    <tr class="table-success">
        <th>Name</th>
        <th>Description</th>
        <th>Owner</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    {% for item in object_list %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.description }}</td>
        <td>{{ item.owner }}</td>
        <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
        <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock %}

mysite/photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}

<h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
<br>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
</form>

{% endblock %}

mysite/photo/templates/photo/album_detail.html
{% extends "base.html" %}
{% load sorl_thumbnail %}


{% block title %}album_detail.html{% endblock %}

{% block extra-style %}
<style>
    thumbnail {
        border: 5px solid #ccc;
    }
</style>
{% endblock %}

{% block content %}

    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span> <!-- h태그 쓰면 줄바꿈 되므로 class로 정의 -->
        <span class="h5 font-italic">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        {% for photo in object.photo_set.all %}
        <div class="col-md-3 mb-5">
            <div class="thumbnail">
                <a href="{{ photo.get_absolute_url }}">
                    {% thumbnail photo.image "256x256" crop="center" as im %}
                    <img src="{{ im.url }}" style="width: 100%;">
                    {% endthumbnail %}
                </a>
            </div>
            <ul>
                <li class="font-italic">{{ photo.title }}</li>
                <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d"}}</li>
            </ul>
        </div>
        {% endfor %}
    </div>

{% endblock %}

mysite/photo/templates/photo/album_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}album_form.html{% endblock %}

{% block content %}

<h1>Album-Photo Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
        {{ form.errors }}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
        {{ formerrors }}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
{% else %}
<form action="" method="post">
{% endif %}
    {% csrf_token %}

    <h4>create or update album contents</h4>

    <fieldset class="card pt-3">

        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>

    </fieldset>
    <br>

    <h4>create or update photo contents</h4>

    <fieldset class="card pt-3">

        {{ formset.managemant_form }} <!-- 폼셋에 들어있는 각 폼을 다루는 경우 반드시 추가, 템플릿 엔진이 폼셋에 들어있는 폼의 개수 등을 인지하는 역할 -->
        {% for form in formset %}
            {{ form.id }}   <!-- 각 폼의 모든 필드를 for이 순회하는 경우가 아니라면 필수로 삽입. 템플릿 엔진이 어느 폼을 처리 중인지 식별할 수 있어야 함-->
            {# form.album #}
        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <hr>
        {% endfor %}

    </fieldset>

    <div class="form-group card py-1">
        <div class="offset-sm-3 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info">
        </div>
    </div>

</form>

{% endblock %}

mysite/photo/templates/photo/album_list.html
{% extends "base.html" %}
{% load sorl_thumbnail %}

{% block title %}album_list.html{% endblock %}

{% block extra-style %}
<style>
    .thumbnail {
        border: 3px solid #ccc;
    }
</style>
{% endblock %}

{% block content %}

{% for item in object_list %}   <!-- Album의 리스트가 담겨있음 -->

<div class="mt-5">
    <a class="h2" href="{% url 'photo:album_detail' item.id %}">
        {{ item.name }}
    </a>&emsp;
    <span class="font-italic h5">{{ item.description }}</span>
</div>

<hr style="margin: 0 0 10px 0;">

<div class="row">
    {% for photo in item.photo_set.all|slice:":5" %} <!-- slice 템플릿 필터는 파이썬 리스트의 슬라이싱과 유사-->
    <div class="col-3 ml-5">
        <div class="thumbnail">
            <a href="{{ photo.get_absolute_url }}">
                {% thumbnail photo.image "256x256" crop="center" as im %}
                <img src="{{ im.url }}" style="width: 100%;">
                {% endthumbnail %}
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endfor %}

{% endblock %}

mysite/photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
<h1>Photo Change - {{user}}</h1>

<table class="table table-striped table-bordered table-condensed">

    <thead>
    <tr class="table-info">
        <th>Album</th>
        <th>Title</th>
        <th>Description</th>
        <th>Owner</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    {% for item in object_list %}
    <tr>
        <td><a href="{% url 'photo:album_detail' item.album.id %}">{{ item.album }}</a></td>
        <td><a href="{% url 'photo:photo_detail' item.id %}">{{ item.title }}</a></td>
        <td>{{ item.description }}</td>
        <td>{{ item.owner }}</td>
        <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
        <td><a href="{% url 'photo:photo_delete' item.id %}">delete</a></td>
    </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock %}

mysite/photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}

<h1>Photo Delete</h1>
<br>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>

{% endblock %}

mysite/photo/templates/photo/photo_confrim_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}

<h1>Photo Delete</h1>
<br>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>

{% endblock %}

mysite/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% block content %}

<h2 class="mt-5">{{ object.title }}</h2>
<div class="row">
    <div class="col-md-9">
        <a href="{{ object.image.url }}">
            <img src="{{ object.image.url }}" style="width: 100%;">
        </a>
    </div>

    <ul class="col-md-3 mt-3">
        <li class="h5">Photo Description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>{% endif %}
        <li class="h5">Date Uploaded</li>
        <p class="font-italic">{{ object.upload_dt }}</p>
        <li class="h5">Album Name</li>
        <p class="font-italic">
            <a href="{% url 'photo:album_detail' object.album.id %}"> {{ object.album.name }}</a>
        </p>
    </ul>
</div>
{% endblock %}

mysite/photo/templates/photo/photo_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}photo_form.html{% endblock %}

{% block content %}
<h1>Photo Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your photo.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
<!-- is_multipart() 메소드는 폼이나 폼셋을 미리 체크해 multipart 인코딩이 필요한지 여부를 알려줌. 반환값이 True이면
     enctype=multipart/form-data로 지정해야함. 여기서는 폼에 이미지 필드가 있으므로 True를 반환함 -->
    <form enctype="multipart/form-data" action="" method="post" class="card pt-3">
{% else %}
    <form action="." method="post" class="card pt-3">
{% endif %}
        {% csrf_token %}
        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">
                    Add Album
                </a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>

{% endblock %}