mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),   # <slug>는 한글 처리가 안되므로 정규식 이용
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),    # 자릿수를 제한하고 싶으면 정규식 이용
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static  # static 함수는 정적 파일을 처리하기 위해 그에 맞는 url 패턴을 반환하는 함수
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('photo/', include('photo.urls')),
    path('blog/', include('blog.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')), # 장고의 인증 URLconf를 가져와서 사용, /login/, /logout/ 등이 정의되어있고 앞에 붙이고 싶은 건 앞에 쓰면 됨.
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# settings.MEDIA_URL로 정의된 /media/ URL 요청이 오면 django.views.static.serve() 뷰 함수가 처리하고
# 이 뷰함수에 document_root = settings.MEDIA_ROOT 키워드 인자가 전달됨.
# static.serve() 함수는 개발용이고 상용에는 httpd, nginx 등 웹 서버 프로그램을 사용함.

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    # 제목의 별칭, unique: 기본키로 사용하기 위해, allow_unicode: 한글 처리
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts' # db에 저장되는 테이블명 default: 앱명_모델클래스명
        ordering = ('-modify_dt',) # 모델 객체 리스트 출력 시 modify_dt 컬럼을 내림차순으로 정렬

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt() # 장고 내장 함수를 이용해 modify_dt 컬럼 기준으로 이전 포스트를 반환

    def get_next(self):
        return self.get_next_by_modify_dt() # 장고 내장 함수를 이용해 modify_dt 컬럼 기준으로 다음 포스트를 반환

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True) # 단어를 알파벳 소문자, 숫자, 밑줄, 하이픈으로만 구성되게 만들어줌
        super().save(*args, **kwargs)   # 부모 클래스의 save 메소드를 호출해서 객체의 내용을 테이블에 반영

mysite/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.conf import settings
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

from blog.models import Post
from blog.forms import PostSearchForm


# ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

# DetailView
class PostDV(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context

# ArchiveView
class PostAV(ArchiveIndexView): # 테이블에서 객체리스트를 받아와 날짜 최신순으로 출력
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView): # 테이블에서 연도를 기준으로 객체리스트를 가져와 객체들이 속한 월을 출력
    model = Post
    date_field = 'modify_dt'    # 수정날짜가 YYYY 연도인 포스트를 검색해 그 포스트의 변경 월을 출력
    make_object_list = True     # 해당 연도에 해당하는 객체의 리스트를 만들어서 템플릿에 넘겨줌

class PostMAV(MonthArchiveView): # 테이블에서 연월을 기준으로 객체리스트를 가져와 출력
    model = Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):  # 테이블에서 연월일을 기준으로 객체리스트를 가져와 출력
    model = Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView): # 테이블에서 날짜가 오늘인 객체 리스트 가져와 출력
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag'] # URL에서 넘어온 값 추출
        return context

class SearchFormView(FormView): # 폼 뷰는 GET요청인 경우 폼을 화면에 보여주고 사용자의 입력을 기다림. 입력 후 제출하면 POST요청으로 접수되어
    form_class = PostSearchForm # FormView 클래스에서 유효성 검사를 함. 데이터가 유효한 경우 form_valid 함수 실행한 후 적절한 URL로 리다이렉트
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']   # 유효성 검사를 통과하면 입력한 데이터가 clead_data 사전에 저장됨
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord)).distinct()
        # Q 객체는 filter 함수의 매칭조건을 다양하게 줄 수 있게 해준다. icontains 연산자는 대소문자를 구분하지 않고 검색, distinct는 중복X

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)
        # 단축함수 render는 템플릿 파일과 컨텍스트 변수를 처리해 최종적으로 HttpResponse 객체를 반환
        # form_valid 함수는 보통 리다이렉트 처리를 위해 HttpResponseRedirect 객체를 반환하지만 여기서는 재정의하여 리다이렉트 사용 X

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    initial = {'slug': 'auto-filling-do-not-input'} # slug는 title 필드로부터 자동으로 채워지는 필드임으로 메세지 삽입, Post모델 정의에 있는 save 함수에서 수행
    # fields = ['title', 'description', 'content', 'tags'] # fields에서 제외하는 방법도 있음
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

mysite/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<h1>Blog List</h1>
<br>

{% for post in posts %}
<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
{{ post.modify_dt|date:"N d, Y" }}
<p>{{ post.description }}</p>
{% endfor %}

<br>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}  <!-- 현재 페이지, 전체페이지 -->

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

<h1>Post Archives until {% now "N d, Y" %}</h1><!-- 현재 날짜와 시간을 원하는 포맷으로 출력 -->

{% for date in date_list %} <!-- DateQuerySet 객체리스트를 담고 있음, 날짜 정보만 추출해서 담고 있음 -->
<a href="{% url 'blog:post_year_archive' date|date:'Y' %}"
   class="btn btn-outline-primary btn-sm mx-1">Year {{ date|date:"Y" }}</a>
{% endfor %}

<br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}

<h1>Post Archive for {{ day|date:"N d, Y" }}</h1><!-- month 해당 연월일을 담은 컨텍스트 변수 -->

<br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ url 'post.get_absolute_url' }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}

<h1>Post Archives for {{ month|date:"N, Y" }}</h1><!-- month 해당 연월을 담은 컨텍스트 변수 -->

<br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1><!-- year 해당 연도를 담은 컨텍스트 변수 -->

{% for date in date_list %}
<a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}"
   class="btn btn-outline-primary btn-sm mx-1">
    {{ date|date:"F" }}
</a>
{% endfor %}

<br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_change_list.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}

<h1>Bookmark Change - {{user}}</h1>
<br>

<table class="table table-bordered table-condensed tabled-striped">

    <thead>
       <tr class="table-primary">
           <th>Title</th>
           <th>Description</th>
           <th>Owner</th>
           <th>Update</th>
           <th>Delete</th>
       </tr>
    </thead>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}

<h1>Post Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
</form>

{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block extra-style %}
<style>
    .post-body {
        width: 80%;
        margin: auto;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
        font-size: 16px;
    }

</style>
{% endblock extra-style %}

{% block content %}
<div class="post-body">
    <h2>{{ object.title }}</h2>

    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            <i class="fas fa-arrow-circle-left"></i> {{ object.get_previous }}
        </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        <i class="fas fa-arrow-circle-left"></i> {{ object.get_next }}
    </a>
        {% endif %}
    </p>

    <p>{{ object.modify_dt|date:"j F Y"}}</p>
    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>

    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %} <!-- 패키지에 정의된 커스텀 태그 사용을 위해 모듈 로딩 -->
        {% get_tags_for_object object as "tags" %} <!-- 커스텀 태그를 이용해 객체에 달린 태그 리스트를 추출해 tags 변수에 할당-->
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
        {% endfor %}
        &emsp;
        <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
    </div>
    <br>

    <div id="disqus_thread"></div>
</div>
{% endblock %}

{% block extra-script %}
<script>
    var disqus_config = function () {
        this.page.url = '{{ disqus_url }}';
        this.page.identifier = '{{ disqus_id }}';
        this.page.title = '{{ disqus_title }}'
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://pydjango-web-programming-97z8swqugh.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();

</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
    Disqus.</a></noscript>
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}

<h1>Post Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your post.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}

    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus"}}
        </div>
    </div>

    <div class="form-group row">
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class="col-sm-5">
            {{ form.slug|add_class:"form-control"|attr:"readonly"}} <!-- 입력 못하게 막아두는 기능 -->
        </div>
        <small class="col form-text text-muted">{{ form.slug.help_text }}</small>
    </div>

    <div class="form-group row">
        {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control"}}
        </div>
        <small class="col form-text text-muted">{{ form.description.help_text }}</small>
    </div>

    <div class="form-group row">
        {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class="col-sm-8">
            {{ form.content|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class="col-sm-5">
            {{ form.tags|add_class:"form-control" }}
        </div>
        <small class="col form-text text-muted">{{ form.tags.help_text }}</small>
    </div>

    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info">
        </div>
    </div>

</form>

{% endblock %}

mysite/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<h1>Blog Search</h1>
<br>

<form action="." method="post">{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br/><br/>

{% if object_list %}

{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_dt|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %} <!-- 검색어는 있지만 결과가 없는 경우(처음 search 화면으로 들어온 경우와 구분하기 위해) -->
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}